config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:index, :create, :new, :update]
  # Defines the root path route ("/")
  root to: "pages#home"
  resources :lambos, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create, :index]
  end
  namespace :owner do
    resources :bookings, only: [:index, :edit]
    resources :lambos, only: :index
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :lambo
  enum status: %i[pending Accepted Rejected]
end

app/models/lambo.rb
class Lambo < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lambos
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
    @lambo = Lambo.find(params[:lambo_id])
  end

  def create
    @lambo = Lambo.find(params[:lambo_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.lambo = @lambo
    # lines 13 to 16 describe what is needed to create a booking
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status, :user_id, :lambo_id)
  end
end

app/controllers/lambos_controller.rb
class LambosController < ApplicationController
    # @lambos = policy_scope(Lambo)
    def index
      @lambos = policy_scope(Lambo)
      if params[:query].present?
        sql_subquery = "model ILIKE :query OR description ILIKE :query"
        @lambos = @lambos.where(sql_subquery, query: "%#{params[:query]}%")
      end
    end

  def new
    @lambo = Lambo.new
    @current_user = current_user
  end

  def create
    @lambo = Lambo.new(lambo_params)
    @lambo.user = current_user
    if @lambo.save
      redirect_to lambos_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @lambo = Lambo.find(params[:id])
    @marker =
      {
        lat: @lambo.latitude,
        lng: @lambo.longitude
      }
  end

  private

  def lambo_params
    params.require(:lambo).permit(:model, :year, :price, :description, :address, photos: [])
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def edit
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status, :user_id, :lambo_id)
  end
end

app/controllers/owner/lambos_controller.rb
class Owner::LambosController < ApplicationController
  def index
    @lambos = policy_scope([:owner, Lambo])
    @bookings = policy_scope([:owner, Booking])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://source.unsplash.com/ze5wHM9kplc" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My Bookings List", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

  <% if current_user %>
<div class="container">
    <div class="row">
    <% @bookings.each do |booking| %>

<div class="col-sm-12 col-md-6 mb-5">
<div class="card" style="width: 18rem;">
<%= cl_image_tag booking.lambo.photos[0].key, class: "card-img-top", crop: :fill %>
  <div class="card-body">
    <h5 class="card-title">Booking Details</h5>
      <p class="card-text">Model: <%= booking.lambo.model%></p>
      <p class="card-text">Status: <%= booking.status%></p>
      <p class="card-text"><%= booking.start_date.strftime ('%b %d,%l:%M %p') %> - <%= booking.end_date.strftime ('%b %d,%l:%M %p') %></p>

          </div>
      </div>
      </div>

  <% end %>
  <% end %>
</div>
</div>


<div class="container">
<div class="row">
<div class="col-md-12 text-end">
  <div class="footer-copyright">
    <i class="fa-regular fa-registered"></i> The WildBunch
  </div>
  </div>
</div>
</div>

app/views/lambos/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://source.unsplash.com/ze5wHM9kplc" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Lambos", new_lambo_path(@current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Lambos", owner_lambos_path(@current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

<div class="container m-2">

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: lambos_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control form-control-lg mb-4",
              placeholder: "Type the model or preference"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-flat mb-4" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container d-flex align-items-center justify-content-center">
  <div class="row">
    <% @lambos.each do |lambo| %>
      <div class="col-sm-12 col-md-6 mb-5">
        <div class="card">
            <%= cl_image_tag lambo.photos[0].key, crop: :fill %>
            <div class="card-infos">
              <div>
                <h2><%= lambo.model %></h2>
                <p class="card-pricing">per day: $<%= lambo.price %></p>
              </div>
              <%= link_to "Details", lambo_path(lambo), class: "btn btn-flat" %>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="text-center">
  <%= link_to "Back", root_path , class: "btn btn-back" %>
</div>

</div>

app/views/lambos/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://source.unsplash.com/ze5wHM9kplc" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Lambos", owner_lambos_path(@current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Lambos", new_lambo_path(@current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>


<div class="container m-5">
<h1>Add your lambo to share</h1>
<%= simple_form_for [@lambo] do |f| %>
  <%= f.input :model, class: "w-50"%>
  <%= f.input :year %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit "Add", class: "btn btn-owner mt-3" %>
  <%= link_to "Back", owner_lambos_path , class: "btn btn-back mt-3" %>
<% end %>
</div>

app/views/lambos/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://source.unsplash.com/ze5wHM9kplc" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Lambos", owner_lambos_path(@current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Lambos", new_lambo_path(@current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

<div id="carouselExampleCaptions" class="carousel slide m-5">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= cl_image_tag @lambo.photos[0].key,crop: :fill,class: "d-block w-100 carousel_images"%>
      <div class="carousel-caption d-none d-md-block">
        <h3><%= @lambo.model %></h3>
        <h5><%= @lambo.year %></h5>
      </div>
    </div>
    <div class="carousel-item">
      <%= cl_image_tag @lambo.photos[1].key, crop: :fill, class: "d-block w-100 carousel_images"%>
      <div class="carousel-caption d-none d-md-block">
        <h3><%= @lambo.model %></h3>
        <h5><%= @lambo.year %></h5>
      </div>
    </div>
    <div class="carousel-item">
      <%= cl_image_tag @lambo.photos[2].key, crop: :fill  , class: "d-block w-100 carousel_images"%>
      <div class="carousel-caption d-none d-md-block">
        <h3><%= @lambo.model %></h3>
        <h5><%= @lambo.year %></h5>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<%# <div class="navbar-vanilla"> %>
    <%# <% reviewers_list = {"Ben - Coding Lord" => image_tag("ben_kiwi.jpeg"),
        "Juri - CSS Empress" => image_tag("juri.jpeg"),
        "The Bowman - HTML Kung-Fu Master" => image_tag("bowman.jpeg"),
        "Chris - JS Reality Bender" => image_tag("chris_sf.jpeg")} %>
<%#
    <%  reviewer_sample = reviewers_list.to_a %>
    <%# <%  reviewer_sample2 = reviewer_sample.sample %>

    <%# <% randome_review = ["You really know what you are doing...Enjoy the Ride!", "People will remember your name!", %>
    <%# "That V12 engine is all you need!", "Your life is complete now!"] %>
    <%# <% randome = randome_review.sample %>
<%# <div class="navbar-vanilla-brand" >" <%= randome</div> %>
    <%# <div class="navbar-vanilla-section"> %>

    <%# </div> %>
    <%# <div class="navbar-vanilla-section">

       <div class="navbar-vanilla-section">
        <div class="players"> <%= reviewer_sample2[0] %>
         <%# <div class="navbar-vanilla-profile">
         <%=reviewer_sample2[1]%>
         <%# </div> %>
       <%# </div> %>
      <%# </div>
    </div> %>
<%# </div> %>








<div class = "d-flex align-items-center justify-content-center">
    <%= link_to "Reserve", new_lambo_booking_path(@lambo), class: "btn btn-book-2 mb-3" %>
</div>

<div class="container contents m-5">
  <div class="row">
    <div class="col-6 car_info mt-4 border-top border-bottom border-secondary border-2">
      <div class="container p-3">
        <div class="row">
          <div class="col-1">
            <i class="fa-solid fa-car-side fa-lg align-middle" style="color: gray;" ></i>
          </div>
          <div class="col-2 d-flex">
            <h3 class="p-2"><%= @lambo.model %></h3>
            <h3 class="p-2"><%= @lambo.year %></h3>
          </div>
        </div>
      </div>
      <div>
      <div class="container">
        <div class="row">
          <div class="col-1">
            <i class="fa-solid fa-dollar-sign fa-lg"style="color: gray;" ></i>
          </div>
          <div class="col-2 d-flex">
            <h3 class="p-2"><%= @lambo.price %>/day</h3>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-1">
           <i class="fa-solid fa-circle-info"style="color: gray;"></i>
          </div>
          <div class="col-12 d-flex">
            <h4 class="p-2"><%= @lambo.description %></h4>
          </div>
          <div class="col-1">
            <i class="fa-solid fa-location-dot" style="color: gray;"></i>
          </div>
          <div class="col-12 d-flex">
            <h4 class="p-2"><%= @lambo.address %></h4>
          </div>
        </div>
      </div>
  </div>
</div>
     <div class="col-6 car_location mt-4">
      <div style="width: 100%; height: 600px;"
        data-controller="map"
        data-map-marker-value="<%= @marker.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>



<%# <div class = "email text-center ">Please contact <%= @lambo.user.email  if you have questions</div> %>



<div class="container">
<div class="row">
<div class="col-md-12 text-end">
  <div class="footer-copyright">
    <i class="fa-regular fa-registered"></i> The WildBunch
  </div>
  </div>
</div>
</div>

app/views/owner/bookings/_form.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://source.unsplash.com/ze5wHM9kplc" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Lambos", owner_lambos_path(@current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Lambos", new_lambo_path(@current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

<%= simple_form_for [@lambo] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.submit class: 'btn btn-flat' %>
<% end %>

app/views/owner/bookings/edit.html.erb
<div class="container mt-5">
  <h1>Edit Booking</h1>

  <%= render "form", task: @booking %>

  <hr>
  <%= link_to owner_bookings_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>
</div>

app/views/owner/bookings/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://source.unsplash.com/ze5wHM9kplc" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Lambos", owner_lambos_path(@current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Lambos", new_lambo_path(@current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

  <% if current_user %>
  <div class="container">
<div class="row">
    <% @bookings.each do |booking| %>

<div class="col-sm-12 col-md-6 mb-5">
<div class="card" style="width: 18rem;">
<%= cl_image_tag booking.lambo.photos[0].key, class: "card-img-top", crop: :fill %>
  <div class="card-body">
    <h5 class="card-title">Booking Details</h5>
      <p class="card-text">Model: <%= booking.lambo.model%></p>
      <p class="card-text">Status: <%= booking.status%></p>
      <p class="card-text">Cost: $<%= booking.lambo.price %></p>
      <p class="card-text">Duration: <%= booking.start_date.strftime ('%b %d, %l:%M %p') %> - <%= booking.end_date.strftime ('%b %d, %l:%M %p') %></p>

<div class="booking-actions">
    <% if booking.pending? %>
    <%= simple_form_for booking do |f| %>
    <%= f.input :status, as: :hidden, input_html: { value: 'Accepted'} %>
    <%= f.submit 'Accept', class: 'btn btn-info' %>
    <% end %>
    <%= simple_form_for booking do |f| %>
    <%= f.input :status, as: :hidden, input_html: { value: 'Rejected'} %>
    <%= f.submit 'Reject', class: 'btn btn-light' %>
    <% end %>
    <% else %>
    <p class='booking-tag'><% booking.status %></p>
    <% end %>
</div>

  </div>
</div>
</div>
<% end %>
</div>

</div>
<% end %>


<div class="container">
<div class="row">
<div class="col-md-12 text-end">
  <div class="footer-copyright">
    <i class="fa-regular fa-registered"></i> The WildBunch
  </div>
  </div>
</div>
</div>

app/views/owner/lambos/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://source.unsplash.com/ze5wHM9kplc" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Lambos", owner_lambos_path(@current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Lambos", new_lambo_path(@current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>



<div class="container m-5">
  <div class="row">
    <% @lambos.each do |lambo| %>
      <div class="col-sm-12 col-md-6 mb-5">
        <div class="card">
             <%= cl_image_tag lambo.photos[0].key, crop: :fill %>
            <div class="card-infos">
              <div>
                <h2><%= lambo.model %></h2>
                <p class="card-pricing">per day: $<%= lambo.price %></p>
                  <% if @bookings %>
                  <% @bookings.each do |booking| %>
                    <% if booking.lambo_id === lambo.id %>
                      <% status = booking.status %>
                        <% if status === "pending" %>
                          <p>Not booked yet</p>
                        <% else %>
                          <%= booking.status %>
                        <% end %>
                     <% end %>
                  <% end %>
                  <% else %>
                    <p>Not booked yet</p>
                  <% end %>
              </div>
            </div>
        </div>
      </div>
    <% end %>
  </div>
  <div>
    <%# <%= link_to "Add Lambos", new_lambo_path(@current_user), class: "nav-link btn btn-owner mb-10" %>
    <%= link_to "Bookings list", owner_bookings_path , class: "btn btn-1 mt-3" %>
    <%= link_to "Back", root_path , class: "btn btn-back mt-3" %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container d-flex align-items-center justify-content-center">
  <%= image_tag("lamboland logo.svg") %>
</div>

  <div class="d-flex align-items-center justify-content-center">
    <h1>Lambos. On Demand.</h1>
  </div>

<div class="container text-center m-3">
  <div>
    <%= link_to "Find your lambos", lambos_path, class: "btn btn-main lambos mb-5" %>
  </div>

    <div>
    <% if current_user%>
      <%= link_to "owner's page", owner_lambos_path , class: "btn btn-owner mb-5" %>
    <% end %>
  </div>

  <div>
    <% if current_user%>
      <%= link_to "Sign out", destroy_user_session_path, class: "btn btn-sign sign" %>
    <% else current_user%>
      <%= link_to "sign in", new_user_session_path , class: "btn btn-sign sign" %>
    <% end %>
  </div>
</div>

<%#
<ul id="results" class="list-group list-group-horizontal"></ul>
<div class="row">
  <div class="col pt-1">
    <button class="btn btn-primary btn-lg" data-controller="hello" data-action="click->hello#click">
      Click me!
    </button>
  </div>
</div>
</div> %>